"use client";

import { FormEvent, useMemo, useState } from "react";

type Story = { id:number; category:string; title:string; summary:string; time:string; image:string; author:string };

const stories: Story[] = [
  { id:1, category:"Kesehatan", title:"Tujuh tanda halus anabul perlu diperiksa dokter hewan", summary:"Perubahan kecil pada pola makan, tidur, dan interaksi sering menjadi sinyal pertama yang perlu diperhatikan pawrents.", time:"12 menit lalu", author:"Tim Health Sliva", image:"https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1400&q=85" },
  { id:2, category:"Kucing", title:"Mengapa kucing membutuhkan ruang vertikal di rumah?", summary:"Rak, cat tree, dan area tinggi membantu kucing merasa aman sekaligus tetap aktif.", time:"28 menit lalu", author:"Rani Kusuma", image:"https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85" },
  { id:3, category:"Konservasi", title:"Cara sederhana ikut menjaga satwa liar dari lingkungan rumah", summary:"Pilihan konsumsi dan kebiasaan digital kita dapat memberi dampak nyata bagi konservasi.", time:"1 jam lalu", author:"Dimas Mahendra", image:"https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=900&q=85" },
  { id:4, category:"Burung", title:"Mengenali kebutuhan enrichment untuk burung peliharaan", summary:"Stimulasi yang tepat membantu burung tetap aktif, tenang, dan menunjukkan perilaku alaminya.", time:"2 jam lalu", author:"Nadia Laras", image:"https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85" },
  { id:5, category:"Anjing", title:"Panduan mengajak anjing beradaptasi dengan lingkungan baru", summary:"Rutinitas konsisten, eksplorasi bertahap, dan area aman menjadi fondasi proses adaptasi.", time:"3 jam lalu", author:"Tim Behavior Sliva", image:"https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=85" },
  { id:6, category:"Gaya Hidup", title:"Checklist perjalanan nyaman bersama anabul", summary:"Mulai dari dokumen, kotak P3K, hingga jadwal istirahat yang sering terlupakan.", time:"4 jam lalu", author:"Ayu Sekar", image:"https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=900&q=85" },
];

const categories = ["Semua","Kesehatan","Anjing","Kucing","Burung","Konservasi","Gaya Hidup"];

export default function Newsroom(){
  const [category,setCategory]=useState("Semua");
  const [query,setQuery]=useState("");
  const [selected,setSelected]=useState<Story|null>(null);
  const [subscribed,setSubscribed]=useState(false);
  const latest=useMemo(()=>stories.filter((story)=>(category==="Semua"||story.category===category)&&(`${story.title} ${story.summary}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
  const subscribe=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSubscribed(true)};

  return <main className="min-h-screen bg-[#fafafa] text-[#15263a]">
    <div className="bg-[#0d2942] text-white"><div className="mx-auto flex h-9 max-w-[1240px] items-center gap-3 overflow-hidden px-4"><span className="shrink-0 rounded bg-[#ff5b4d] px-2 py-1 text-[8px] font-black uppercase tracking-wider">Sliva update</span><p className="truncate text-[9px] text-slate-300">Panduan kesehatan, kesejahteraan, dan cerita satwa terpercaya untuk Indonesia.</p><span className="ml-auto hidden shrink-0 text-[8px] text-slate-400 sm:block">Rabu, 26 Agustus 2026</span></div></div>
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1240px] items-center px-4"><button aria-label="Buka menu" className="mr-3 grid size-10 place-items-center rounded-xl border border-slate-200 text-lg lg:hidden">≡</button><a href="#top" className="text-2xl font-black tracking-[-.05em]">sliva<span className="text-sky-500">news</span><i className="ml-1 inline-block size-2 rounded-full bg-[#ff5b4d]"/></a><nav className="ml-10 hidden items-center gap-6 lg:flex">{["Beranda","Terpopuler","Video","Foto","Opini"].map((item,index)=><a className={`text-[10px] font-bold ${index===0?"text-sky-600":"text-slate-500 hover:text-slate-900"}`} href="#latest" key={item}>{item}</a>)}</nav><label className="ml-auto flex h-10 w-40 items-center gap-2 rounded-xl bg-slate-100 px-3 sm:w-64"><span className="text-slate-400">⌕</span><input value={query} onChange={(e)=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-[10px] outline-none" placeholder="Cari berita hewan..."/></label><button aria-label="Notifikasi" className="ml-2 grid size-10 place-items-center rounded-xl border border-slate-200">♧</button></div><div className="border-t border-slate-100"><div className="hide-scroll mx-auto flex max-w-[1240px] gap-2 overflow-x-auto px-4 py-2">{categories.map((item)=><button onClick={()=>setCategory(item)} className={`shrink-0 rounded-full px-4 py-2 text-[9px] font-bold ${category===item?"bg-[#0d2942] text-white":"bg-slate-100 text-slate-500 hover:bg-slate-200"}`} key={item}>{item}</button>)}</div></div></header>

    <div id="top" className="mx-auto max-w-[1240px] px-4 py-7"><div className="mb-5 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-sky-600">Pilihan redaksi</p><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Cerita penting hari ini.</h1></div><span className="hidden text-[9px] text-slate-400 sm:block">Konten edukasi · ditinjau editor</span></div>
      <section className="grid gap-4 lg:grid-cols-[1.45fr_.75fr]">
        <button onClick={()=>setSelected(stories[0])} className="group relative min-h-[440px] overflow-hidden rounded-[26px] bg-slate-900 text-left text-white"><img alt="Anjing sedang diperiksa" src={stories[0].image} className="absolute inset-0 h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105"/><span className="absolute inset-0 bg-gradient-to-t from-[#07131e] via-[#07131e]/30 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><span className="rounded-full bg-sky-500 px-3 py-2 text-[8px] font-black uppercase tracking-wider">{stories[0].category}</span><h2 className="mt-4 max-w-2xl text-2xl font-black leading-tight tracking-tight sm:text-4xl">{stories[0].title}</h2><p className="mt-3 max-w-xl text-xs leading-6 text-slate-200">{stories[0].summary}</p><div className="mt-5 flex items-center gap-3 text-[9px] text-slate-300"><span>{stories[0].author}</span><i className="size-1 rounded-full bg-slate-400"/><time>{stories[0].time}</time></div></div></button>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{stories.slice(1,3).map((story)=><button onClick={()=>setSelected(story)} key={story.id} className="group grid min-h-[210px] overflow-hidden rounded-[24px] border border-slate-200 bg-white text-left shadow-sm sm:block lg:grid-cols-[.8fr_1fr]"><div className="h-28 overflow-hidden sm:h-32 lg:h-full"><img alt="" src={story.image} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-4"><span className="text-[8px] font-black uppercase tracking-wider text-sky-600">{story.category}</span><h3 className="mt-2 text-sm font-extrabold leading-5 group-hover:text-sky-600">{story.title}</h3><time className="mt-3 block text-[8px] text-slate-400">{story.time}</time></div></button>)}</div>
      </section>

      <div id="latest" className="mt-9 grid gap-8 xl:grid-cols-[1fr_330px]"><section><div className="mb-5 flex items-center justify-between border-b-2 border-[#0d2942] pb-3"><h2 className="text-lg font-black">{category==="Semua"?"Berita terbaru":category}</h2><span className="text-[9px] text-slate-400">{latest.length} artikel</span></div><div className="grid gap-4 sm:grid-cols-2">{latest.map((story)=><button onClick={()=>setSelected(story)} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white text-left transition hover:-translate-y-0.5 hover:shadow-xl" key={story.id}><div className="h-44 overflow-hidden"><img alt="" src={story.image} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-4"><div className="flex items-center justify-between"><span className="text-[8px] font-black uppercase tracking-wider text-sky-600">{story.category}</span><time className="text-[8px] text-slate-400">{story.time}</time></div><h3 className="mt-2 text-sm font-extrabold leading-5 group-hover:text-sky-600">{story.title}</h3><p className="mt-2 line-clamp-2 text-[10px] leading-5 text-slate-500">{story.summary}</p></div></button>)}{!latest.length&&<div className="col-span-full rounded-2xl border border-dashed border-slate-300 p-12 text-center text-xs text-slate-400">Berita yang Anda cari belum ditemukan.</div>}</div></section>
        <aside className="space-y-5"><section className="rounded-3xl bg-[#0d2942] p-5 text-white"><p className="text-[9px] font-black uppercase tracking-widest text-sky-300">Paling dibaca</p><div className="mt-4 divide-y divide-white/10">{stories.slice(0,5).map((story,index)=><button onClick={()=>setSelected(story)} className="flex w-full gap-3 py-4 text-left" key={story.id}><span className="text-2xl font-black text-white/15">0{index+1}</span><span><strong className="block text-[10px] leading-4">{story.title}</strong><small className="mt-1 block text-[8px] text-slate-400">{story.time}</small></span></button>)}</div></section><section className="rounded-3xl bg-gradient-to-br from-sky-500 to-cyan-400 p-6 text-white"><span className="text-2xl">✉</span><h3 className="mt-4 text-xl font-black tracking-tight">The Daily Paw</h3><p className="mt-2 text-[10px] leading-5 text-sky-50">Ringkasan berita dan panduan pilihan, dikirim tanpa spam.</p>{subscribed?<div className="mt-5 rounded-xl bg-white/20 p-4 text-[10px] font-bold">✓ Email berhasil didaftarkan.</div>:<form onSubmit={subscribe} className="mt-5"><input required type="email" className="w-full rounded-xl border border-white/30 bg-white/15 px-4 py-3 text-[10px] text-white outline-none placeholder:text-white/70" placeholder="Email Anda"/><button className="mt-2 w-full rounded-xl bg-white py-3 text-[10px] font-black text-sky-600">Berlangganan gratis</button></form>}</section></aside>
      </div>
    </div>

    <footer className="mt-16 border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-4 px-4 py-10 sm:flex-row sm:items-center sm:justify-between"><strong className="text-lg">sliva<span className="text-sky-500">news</span></strong><p className="text-[9px] text-slate-400">Berita hewan, pet care, fauna, dan konservasi untuk Indonesia.</p><div className="flex gap-4 text-[9px] font-bold text-slate-500"><a href="#">Tentang</a><a href="#">Redaksi</a><a href="#">Pedoman Media</a></div></div></footer>

    {selected&&<div className="fixed inset-0 z-50 grid place-items-end bg-[#061421]/75 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={()=>setSelected(null)}><article onMouseDown={(e)=>e.stopPropagation()} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-white text-[#15263a] shadow-2xl sm:rounded-3xl"><div className="relative h-64 overflow-hidden"><img alt="" src={selected.image} className="h-full w-full object-cover"/><span className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><button aria-label="Tutup artikel" onClick={()=>setSelected(null)} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white text-xl shadow-lg">×</button><span className="absolute bottom-5 left-6 rounded-full bg-sky-500 px-3 py-2 text-[8px] font-black uppercase text-white">{selected.category}</span></div><div className="p-6 sm:p-8"><h2 className="text-2xl font-black leading-tight sm:text-3xl">{selected.title}</h2><div className="mt-4 flex gap-2 text-[9px] text-slate-400"><span>{selected.author}</span><span>·</span><time>{selected.time}</time></div><p className="mt-6 text-sm font-semibold leading-7 text-slate-600">{selected.summary}</p><p className="mt-4 text-xs leading-7 text-slate-500">Perhatikan perubahan perilaku yang berlangsung konsisten dan catat kapan gejala mulai muncul. Informasi yang lengkap membantu dokter hewan melakukan evaluasi lebih terarah. Konten ini bersifat edukasi dan tidak menggantikan pemeriksaan profesional.</p><div className="mt-7 rounded-2xl bg-sky-50 p-4 text-[10px] leading-5 text-sky-800"><b>Catatan redaksi:</b> Materi kesehatan Sliva News ditulis untuk edukasi pawrents dan selalu mendorong konsultasi dengan tenaga medis hewan.</div></div></article></div>}
  </main>
}
